const {
  PG_HOST,
  PG_PORT,
  PG_DATABASE,
  PG_USERNAME,
  PG_PASSWORD,
  PRODUCTS_QUEUE_URL,
  CREATE_PRODUCT_TOPIC_ARN,
} = process.env;

export const config = {
  db: {
    PG_HOST,
    PG_PORT: +PG_PORT,
    PG_DATABASE,
    PG_USERNAME,
    PG_PASSWORD,
  },
  PRODUCTS_QUEUE_URL,
  CREATE_PRODUCT_TOPIC_ARN
};
