swagger: "2.0"
info:
  description: "Rs School Merch BE"
  version: "1.0.0"
  title: "Rs School Merch BE"
  contact:
    email: "max.jsspec@gmail.com"
tags:
- name: "products"
  description: "Products API"
schemes:
- "https"
paths:
  /products:
    get:
      tags:
      - "products"
      summary: "Get products list"
      operationId: "getAllProducts"
      produces:
      - "application/json"
      responses:
        "200":
          description: "Successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Product"
        "500":
          description: "Internal server error"
    post:
      tags:
        - "products"
      summary: "Create product"
      operationId: "createProduct"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Product object that need to be added to the store"
          required: true
          schema:
            $ref: "#/definitions/Product"
      responses:
        "201":
          description: "Successful operation"
          schema:
            $ref: "#/definitions/Product"
        "400":
          description: "Incorrect request"
          schema:
            type: object
            properties:
              message:
                type: string
              error:
                type: string
        "500":
          description: "Internal server error"
  /products/{productId}:
    get:
      tags:
      - "products"
      summary: "Find product by ID"
      description: "Returns a single product"
      operationId: "getProductById"
      produces:
      - "application/json"
      parameters:
      - name: "productId"
        in: "path"
        description: "ID of product to return"
        required: true
        type: "integer"
      responses:
        "200":
          description: "Successful operation"
          schema:
            $ref: "#/definitions/Product"
        "404":
          description: "Product not found"
        "500":
          description: "Internal server error"
definitions:
  Product:
    type: "object"
    required:
    - "title"
    - "description"
    - "price"
    properties:
      id:
        type: "integer"
        format: "string"
      title:
        type: "string"
        example: "Product"
      description:
        type: "string"
        example: "Description"
      price:
        type: "integer"
        example: 30
      count:
        type: "integer"
        example: 5
